language: node_js
node_js:
  - "stable"
install: ./travis-install.sh
script: ./gulp dist && ./gulp links
notifications:
  recipients:
    - rhys@creativekidssa.com.au
cache:
  directories:
    - node_modules
