language: node_js
node_js:
  - "stable"
install: ./travis-install.sh
script: ./gulp dist && ./gulp links
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy_travis.sh
notifications:
  recipients:
    - rhys@creativekidssa.com.au
cache:
  directories:
    - node_modules
